# PRP Configuration Template
# This template provides default configuration for PRP system

prp_configuration:
  version: "1.0.0"

  analysis:
    external_research_enabled: true
    pattern_discovery_depth: "comprehensive"  # basic, standard, comprehensive
    research_cache_ttl: "24h"
    max_patterns_per_analysis: 50

  blueprint:
    template_validation: "strict"  # lenient, standard, strict
    pattern_consistency_threshold: 0.85
    quality_gates_required: true
    max_tasks_per_blueprint: 100

  execution:
    parallel_execution: false  # Start with sequential for stability
    real_time_monitoring: true
    automatic_rollback: true
    max_concurrent_tasks: 5

  learning:
    pattern_learning_enabled: true
    cross_project_sharing: true
    template_evolution: true
    success_tracking: true

  advanced:
    debug_mode: false
    performance_profiling: false
    detailed_logging: false
    backup_before_execution: true

  agents:
    default_model: "opus"
    timeout_seconds: 300
    retry_attempts: 3

    specialist_assignments:
      codebase_analysis: "codebase-research-specialist"
      requirements_analysis: "requirements-analyst"
      external_research: "external-research-specialist"
      blueprint_creation: "blueprint-architect"
      security_validation: "security-specialist"
      performance_validation: "performance-optimizer"

  storage:
    base_path: "~/.claude/prp"
    backup_retention_days: 30
    analysis_retention_days: 90
    blueprint_retention_days: 180

  notifications:
    enabled: true
    methods: ["console"]  # console, file, webhook
    levels: ["error", "warning", "success"]

  quality_gates:
    default_gates:
      - "pattern_consistency"
      - "security_validation"
      - "test_coverage"

    thresholds:
      pattern_consistency_min: 0.80
      test_coverage_min: 0.75
      security_score_min: 0.90